#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2008 Guilherme Starvaggi Franca
#
# This file is part of Smurf.
#
# Smurf is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Smurf is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Smurf.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: G. S. Franca <guifranca@gmail.com>

import libcurses
import sys
try:
    win = libcurses.begin_curses()
    import filemanager
    if len(sys.argv) > 1:
        dir = sys.argv[1]
    else:
        dir = ''
    fm = filemanager.FileManager(win, dir)
    fm.loop()
except KeyboardInterrupt:
    pass
except:
    libcurses.end_curses()
    raise
finally:
    libcurses.end_curses()
print
